# Generated by Django 3.2.18 on 2023-04-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Reviews',
        ),
    ]
